version: "3.8"

services:

  # MS SQL Server
  # https://hub.docker.com/_/microsoft-mssql-server
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Example@1"
    volumes:
    #   - mssql:/var/opt/mssql/data
      - ./docker_sqlserver:/docker_init
    command: sh -c ' chmod +x /docker_init/entrypoint.sh; /docker_init/entrypoint.sh & /opt/mssql/bin/sqlservr;'

  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=sqlserver
    depends_on:
      - sqlserver
    ports:
      - 8080:8080
